apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ray-training-dev

resources:
  - ../../base
  - resource-quotas.yaml

patchesStrategicMerge:
  - ray-cluster-patch.yaml

commonLabels:
  environment: dev

images:
  - name: rayproject/ray
    newTag: 2.9.0-py310
