apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - resource-quotas.yaml

patchesStrategicMerge:
  - ray-cluster-patch.yaml
  - notebooks-patch.yaml  # Add this line
  - mlflow-patch.yaml     # Add this line

commonLabels:
  environment: dev

images:
  - name: rayproject/ray
    newTag: 2.9.0-py310
  - name: jupyter/datascience-notebook  # Add this if you want to pin notebook image
    newTag: latest
