apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - resource-quotas.yaml

patches:
  - path: ray-cluster-patch.yaml
  - path: notebooks-patch.yaml
  - path: mlflow-patch.yaml- ray-cluster-patch.yaml

commonLabels:
  environment: dev

images:
  - name: rayproject/ray
    newTag: 2.9.0-py310
  - name: jupyter/datascience-notebook  # Add this if you want to pin notebook image
    newTag: latest
