apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterhub
spec:
  template:
    spec:
      containers:
      - name: jupyterhub
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
