apiVersion: v1
kind: ConfigMap
metadata:
  name: jupyterhub-config
data:
  jupyterhub_config.py: |
    import os
    from dockerspawner import DockerSpawner
    
    c = get_config()
    
    # Basic config
    c.JupyterHub.hub_ip = '0.0.0.0'
    c.JupyterHub.hub_port = 8081
    c.JupyterHub.port = 8000
    
    # Use DockerSpawner for single-user servers
    c.JupyterHub.spawner_class = DockerSpawner
    c.DockerSpawner.image = 'jupyter/datascience-notebook:latest'
    c.DockerSpawner.network_name = 'bridge'
    c.DockerSpawner.remove = True
    
    # Environment variables for notebooks
    c.DockerSpawner.environment = {
        'RAY_ADDRESS': 'ray://ray-client-service.ray-training-dev.svc.cluster.local:10001',
        'MLFLOW_TRACKING_URI': 'http://mlflow-service.ray-training-dev.svc.cluster.local:5000'
    }
    
    # Simple authenticator (change for production)
    c.JupyterHub.authenticator_class = 'jupyterhub.auth.DummyAuthenticator'
    c.DummyAuthenticator.password = 'research123'
    
    # Admin users
    c.Authenticator.admin_users = {'admin'}
