# base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces
  - ray-cluster

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/part-of: ray-gke-infrastructure
  app.kubernetes.io/managed-by: kustomize

---
# base/namespaces/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml

---
# base/namespaces/namespaces.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: data-pipeline-dev
  labels:
    environment: dev
    workload-type: data-pipeline
---
apiVersion: v1
kind: Namespace
metadata:
  name: ray-training-dev
  labels:
    environment: dev
    workload-type: ml-training
---
apiVersion: v1
kind: Namespace
metadata:
  name: notebooks-dev
  labels:
    environment: dev
    workload-type: interactive

---
# base/ray-cluster/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - services.yaml
  - ray-cluster.yaml

commonLabels:
  app.kubernetes.io/component: ray-cluster
