apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces
  - ray-cluster

commonLabels:
  app.kubernetes.io/part-of: ray-gke-infrastructure
  app.kubernetes.io/managed-by: kustomize
