apiVersion: v1
kind: Service
metadata:
  name: ray-client-service
  labels:
    app: ray-head
spec:
  selector:
    ray.io/node-type: head  # This should match your existing Ray head labels
  ports:
  - name: ray-client
    port: 10001
    targetPort: 10001
  - name: dashboard
    port: 8265
    targetPort: 8265
  type: ClusterIP
